"""initial postgres prd schema

Revision ID: 67930e7cce7a
Revises: 
Create Date: 2026-06-08 18:58:16.930945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67930e7cce7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # pgcrypto provides gen_random_uuid() used as the server-side default for
    # the PRD UUID primary keys below.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('country_rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('rate_name', sa.String(length=64), nullable=False),
    sa.Column('queried_for_date', sa.Date(), nullable=False),
    sa.Column('hourly', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('monthly_gross', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_valid_from', sa.Date(), nullable=False),
    sa.Column('period_valid_to', sa.Date(), nullable=True),
    sa.Column('period_verified_at', sa.Date(), nullable=False),
    sa.Column('period_verified_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country_rate_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_rate_snapshots_country'), ['country'], unique=False)

    op.create_table('nbp_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('rate_pln', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('table_no', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'effective_date', name='uq_nbp_currency_date')
    )
    with op.batch_alter_table('nbp_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nbp_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_nbp_rates_effective_date'), ['effective_date'], unique=False)

    op.create_table('organisation',
    sa.Column('national_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('national_id')
    )
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_country'), ['country'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'FLEET_MANAGER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)

    op.create_table('drivers',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=3), nullable=False),
    sa.Column('identification_id', sa.String(length=30), nullable=False),
    sa.Column('pesel', sa.String(length=11), nullable=True),
    sa.Column('passport_number', sa.String(length=32), nullable=True),
    sa.Column('tachograph_card_number', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organisation_uuid', sa.Uuid(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_uuid'], ['organisation.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('identification_id'),
    sa.UniqueConstraint('pesel'),
    sa.UniqueConstraint('tachograph_card_number')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_organisation_uuid'), ['organisation_uuid'], unique=False)

    op.create_table('vehicles',
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('registration_plate', sa.String(length=20), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organisation_uuid', sa.Uuid(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_uuid'], ['organisation.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('vin')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_organisation_uuid'), ['organisation_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_registration_plate'), ['registration_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_type'), ['vehicle_type'], unique=False)

    op.create_table('driver_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('contract_type', sa.Enum('UMOWA_O_PRACE', 'UMOWA_ZLECENIA', 'B2B', name='contracttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('base_salary_pln', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_norm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_contracts_driver_id'), ['driver_id'], unique=False)

    op.create_table('driver_document',
    sa.Column('driver_uuid', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['driver_uuid'], ['drivers.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('driver_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_document_driver_uuid'), ['driver_uuid'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('trip_number', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_trip_number'), ['trip_number'], unique=False)

    op.create_table('vehicle_document',
    sa.Column('vehicle_uuid', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_uuid'], ['vehicles.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('vehicle_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_document_vehicle_uuid'), ['vehicle_uuid'], unique=False)

    op.create_table('trip_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('segment_type', sa.Enum('TRANSIT', 'BILATERAL', 'CABOTAGE', 'CROSS_TRADE', name='segmenttype'), nullable=False),
    sa.Column('work_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rate_name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_segments_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_segments_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_segments_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_segments_work_date'))
        batch_op.drop_index(batch_op.f('ix_trip_segments_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_segments_country'))

    op.drop_table('trip_segments')
    with op.batch_alter_table('vehicle_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_document_vehicle_uuid'))
        batch_op.drop_index(batch_op.f('ix_vehicle_document_document_type'))

    op.drop_table('vehicle_document')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_trip_number'))
        batch_op.drop_index(batch_op.f('ix_trips_driver_id'))

    op.drop_table('trips')
    with op.batch_alter_table('driver_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_document_driver_uuid'))
        batch_op.drop_index(batch_op.f('ix_driver_document_document_type'))

    op.drop_table('driver_document')
    with op.batch_alter_table('driver_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_contracts_driver_id'))

    op.drop_table('driver_contracts')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_type'))
        batch_op.drop_index(batch_op.f('ix_vehicles_registration_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_organisation_uuid'))

    op.drop_table('vehicles')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_organisation_uuid'))
        batch_op.drop_index(batch_op.f('ix_drivers_last_name'))

    op.drop_table('drivers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))

    op.drop_table('users')
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_country'))

    op.drop_table('organisation')
    with op.batch_alter_table('nbp_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nbp_rates_effective_date'))
        batch_op.drop_index(batch_op.f('ix_nbp_rates_currency'))

    op.drop_table('nbp_rates')
    with op.batch_alter_table('country_rate_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_rate_snapshots_country'))

    op.drop_table('country_rate_snapshots')
    # ### end Alembic commands ###