"""vacation_leave_tables

Revision ID: e70e4340e789
Revises: e5f6a7b8c9d0
Create Date: 2026-06-09 23:00:40.852811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e70e4340e789'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_accounts',
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('public_holidays',
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('country', 'day', name='uq_holiday_country_day')
    )
    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_holidays_day'), ['day'], unique=False)

    op.create_table('leave_entitlements',
    sa.Column('driver_uuid', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('base_days', sa.Integer(), nullable=False),
    sa.Column('carried_over_days', sa.Integer(), nullable=False),
    sa.Column('adjustment_days', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['driver_uuid'], ['drivers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('driver_uuid', 'year', name='uq_entitlement_driver_year')
    )
    with op.batch_alter_table('leave_entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_entitlements_driver_uuid'), ['driver_uuid'], unique=False)

    op.create_table('leave_entries',
    sa.Column('driver_uuid', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ANNUAL', 'ON_DEMAND', 'SICK', 'UNPAID', 'OTHER', name='leavekind'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('counted_days', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GOOGLE', name='leavesource'), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_etag', sa.String(length=128), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_uuid'], ['drivers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('google_event_id')
    )
    with op.batch_alter_table('leave_entries', schema=None) as batch_op:
        batch_op.create_index('ix_leave_driver_start', ['driver_uuid', 'start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_entries_driver_uuid'), ['driver_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_entries_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_entries_start_date'))
        batch_op.drop_index(batch_op.f('ix_leave_entries_driver_uuid'))
        batch_op.drop_index('ix_leave_driver_start')

    op.drop_table('leave_entries')
    with op.batch_alter_table('leave_entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_entitlements_driver_uuid'))

    op.drop_table('leave_entitlements')
    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_holidays_day'))

    op.drop_table('public_holidays')
    op.drop_table('google_calendar_accounts')
    # ### end Alembic commands ###
